# Generated by Django 5.1 on 2024-09-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_alter_comment_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
