# Generated by Django 5.1 on 2024-10-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_profile_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visibility_status',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], default='Visible', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='Published', max_length=20),
        ),
    ]
