# Generated by Django 5.1 on 2024-10-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_blog_visibility_status_alter_blog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='visibility_status',
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(default='Published', max_length=20),
        ),
    ]
